pipeline {
    agent any
    tools {
        maven 'Maven_3.3.9'
        jdk 'jdk-11.0.2'
    }
    stages {
        stage('Initialize Tools') {
            steps {
                sh '''
                    echo "PATH = ${PATH}"
                    echo "JAVA_HOME = ${JAVA_HOME}"
                    echo "M2_HOME = ${M2_HOME}"
                '''
            }
        }
        stage('Build Project1') {
            steps {
                sh 'mvn -f Project1/pom.xml clean install'
            }
        }
        stage('Archive JAR') {
            steps {
                archiveArtifacts artifacts: 'Project1target/*.jar', allowEmptyArchive: true
            }
        }
    }
}
