echo "Building Project1"
tools {
    maven 'Maven_3.3.9'
    jdk 'jdk-11.0.2'
}

stage('Tools Initialize') {
    steps {
        sh '''
            echo "PATH = ${PATH}"
            echo "M2_HOME = ${M2_HOME}"
        '''
    }
}

stage('Build Project1') {
    steps {
        sh 'mvn clean install'
    }
}
stage('Archive JAR') {
    steps {
        archiveArtifacts artifacts: 'target/*.jar', allowEmptyArchive: true
    }
}
