pipeline {
    agent any
		tools { 
        maven 'Maven_3.3.9' 
        jdk 'jdk-11.0.2' 
    }	
    stages {
			stage ('Tools Initialize') {
            steps {
                sh '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                ''' 
            }
        }
        stage('Build Project1') {
            steps {
                sh 'mvn -f Project3/pom.xml clean install'
            }
        }
        stage('Archive JAR') {
            steps {
                archiveArtifacts artifacts: 'Project3/target/*.jar', allowEmptyArchive: true
            }
        }
    }
}
